apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: loserforever/chatssy-server-dev
          ports:
            - containerPort: 3000
          env:
            - name: SESSION_SECRET
              value: "4e511eeff9e8f4d5af2ebadf3ba443e624c384519992614cac941d2751a78184628971f8d82fe681279189976df964fa"
            - name: SESSION_MAX_AGE
              value: "30days"
            - name: MONGO_URI
              value: "mongodb+srv://admin:anchuoicanai@chatssy.lgekg.mongodb.net/?retryWrites=true&w=majority"
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CACHE_TTL
              value: "100"
            - name: PASSWORD_SALT_ROUNDS
              value: "12"
            - name: GOOGLE_ADMIN_EMAIL_ADDRESS
              value: "chatssy881@gmail.com"
            - name: GOOGLE_CLIENT_ID
              value: "21492346218-2lbic5vbi1fonq0m73mbo94i7srvl22d.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              value: "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"
            - name: GOOGLE_MAILER_REFRESH_TOKEN
              value: "1//04i2wszFiJ2XdCgYIARAAGAQSNwF-L9Ir0ugCe8_yoL0IOdsH0Wo0Cvalqzpax8NNkKk_5wQ3FmwNiLcTKVt7qiJgzhkYovCo3Rs"
            - name: MESSAGE_BUCKET_MAX_COUNT
              value: "3"
